### ISSUE TITLE
Hope for some modifications

### ISSUE THREAD

**Issue by ADeerWhoLovesEveryone** [ykundesu/SuperNewRoles#1262]
Hello
In the introduction of "警察医", "Republic of Taiwan" appeared, we hope to change it to "Chinese Taipei", we think "Republic of Taiwan" is promoting Taiwan independence, thank you

**Comment by Kurato-Tsukishiro** [comment]
@ADeerWhoLovesEveryone 

> こんにちは。 「警察医」の紹介で「台湾共和国」と出てきましたが、「チャイニーズタイペイ」に変更したいと思います。「台湾共和国」は台湾独立を推進していると思います。ありがとうございます

Since the idea originated from the "Medical Examination Certificate", which is an official document in Japan, the date notation uses the date notation used in official documents of the place where the language is mainly used.

Also, since the name of the calendar in C# was "TaiwanCalendar", the English translation is based on this name.
(The Japanese calendar used in official documents in Japan is "JapaneseCalendar".)
![image](https://github.com/ykundesu/SuperNewRoles/assets/104145991/63cdfc2c-2b2e-4deb-adfe-7e5e5723a5b7)


If you really "support independence," you don't need to create a setting, and the TChinece display will reflect the [民国歴].

Is it not enough to have a setting?

(This English text was translated by machine, and when I re-translated it into Japanese and checked it, it was quite provocative.
Since we did not have the technology to correct it, we are using it as it is. Our apologies.

The original Japanese text is the correct response).

```
アイデア元は日本の公的な書類である「死体検案書」である為、日付表記では、主にその言語が使われる場所の公的書類に使われている日付表記を使用しています。

又, C#での暦の名前が「TaiwanCalendar」であった為, 英語翻訳はこれをそのまま用いたものになります。
(日本の公的な書類に用いられている「和暦」の場合は"JapaneseCalendar"となっています。)
本当に「独立を支持している」のであれば設定を作らずに、TChinece表示の場合[民国歴]を反映させています。

設定があるだけではだめなのでしょうか。

(この英文は機械翻訳を使用しており、日本語に再翻訳して確認した所かなり挑発的な文章になっておりました。
修正する技術がなかった為、そのまま利用しております。申し訳ありません。

翻訳元の日本語文が正確な回答文となります。)
```

**Comment by ADeerWhoLovesEveryone** [comment]
ご回答ありがとうございます

**Comment by ADeerWhoLovesEveryone** [comment]
あなたの答えをありがとう、私はあなたのmodがどんどん良くなっていることを願っています
